### ISSUE TITLE
Unable to open object (object 'experiments' doesn't exist)

### ISSUE THREAD

**Issue by ijhoskins** [ribosomeprofiling/ribopy#15]
Getting an error with process 'put_rnaseq_into_ribo'

The RiboFlow config looks OK to me (attached for reference).

I am able to run the test data.

```
+ ribopy rnaseq set -n GSM1503442_MDA-MB-231 -a GSM1503442_MDA-MB-231.merged.pre_dedup.bed -f bed --force input.1
Traceback (most recent call last):
  File "/home/ihoskins/miniconda3/envs/ribo/bin/ribopy", line 8, in <module>
    sys.exit(cli())
  File "/home/ihoskins/miniconda3/envs/ribo/lib/python3.7/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ihoskins/miniconda3/envs/ribo/lib/python3.7/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ihoskins/miniconda3/envs/ribo/lib/python3.7/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ihoskins/miniconda3/envs/ribo/lib/python3.7/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ihoskins/miniconda3/envs/ribo/lib/python3.7/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ihoskins/miniconda3/envs/ribo/lib/python3.7/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ihoskins/miniconda3/envs/ribo/lib/python3.7/site-packages/ribopy/cli/rnaseq.py", line 54, in set
    force         = force)
  File "/home/ihoskins/miniconda3/envs/ribo/lib/python3.7/site-packages/ribopy/core/verify.py", line 104, in cli_func_wrapper
    return func(*args, **kwargs)
  File "/home/ihoskins/miniconda3/envs/ribo/lib/python3.7/site-packages/ribopy/rnaseq.py", line 231, in set_rnaseq_wrapper
    experiment_handle = ribo_handle[EXPERIMENTS_name][name]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/ihoskins/miniconda3/envs/ribo/lib/python3.7/site-packages/h5py/_hl/group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'experiments' doesn't exist)"
```

[appris copy.yaml.zip](https://github.com/ribosomeprofiling/ribopy/files/14350032/appris.copy.yaml.zip)

**Comment by ijhoskins** [comment]
@hakanozadam any thoughts on what might be going on here?

**Comment by ijhoskins** [comment]
If I set do_rnaseq = false RiboFlow completes without error but produces no .ribo file.

With do_rnaseq = true or false, I do not see the create_ribo process. This cause an error during the put_rnaseq_into_ribo process with do_rnaseq = true .

```
N E X T F L O W  ~  version 19.04.1
Launching `/home/ihoskins/riboflow/RiboFlow.groovy` [grave_mclean] - revision: 1eb5b20f2c
[warm up] executor > local
executor >  local (31)
[af/e988b3] process > clip                               [100%] 3 of 3 ✔
[7b/b42b80] process > write_fastq_correspondence         [100%] 1 of 1 ✔
[d1/96ca53] process > filter                             [100%] 3 of 3 ✔
[c4/e5665a] process > transcriptome_alignment            [100%] 3 of 3 ✔
[ea/cce9e3] process > quality_filter                     [100%] 3 of 3 ✔
[b8/c14f7e] process > merge_transcriptome_alignment      [100%] 3 of 3 ✔
[9a/e9604e] process > bam_to_bed                         [100%] 3 of 3 ✔
[f9/85653a] process > individual_alignment_stats         [100%] 3 of 3 ✔
[e9/8061c2] process > add_sample_index_col_to_bed        [100%] 3 of 3 ✔
[b0/74ab3f] process > sum_individual_alignment_stats     [100%] 3 of 3 ✔
[8f/078860] process > combine_individual_alignment_stats [100%] 1 of 1 ✔
[d2/fd6879] process > combine_merged_alignment_stats     [100%] 1 of 1 ✔
[62/a78b37] process > publish_stats                      [100%] 1 of 1 ✔
Completed at: 22-Feb-2024 18:58:24
Duration    : 2h 20m 58s
CPU hours   : 9.2
Succeeded   : 31
```
